apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: backend-app
          image: 394952106077.dkr.ecr.ap-northeast-2.amazonaws.com/backend-app:2
