apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml # 네임스페이스 먼저 생성
  - ../../base
patches:
  - path: deployment_patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: backend-app
